config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #C
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  #R
  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show'

  #U
  get 'tasks/:id/edit', to: 'tasks#edit'
  patch 'tasks/:id', to: 'tasks#update', as: "task"
  #D
  delete 'tasks/:id', to: 'tasks#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  #R

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  #C
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  #U
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  #D
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit <em><%=@task.title%></em></h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed  %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Task list:</h1>

<fieldset>
  <% @tasks.each do |t| %>
    <% if t.completed %>
      <div>
        <input type="checkbox" name="task" checked>
        <label for="task"><%= link_to t.title, "tasks/#{t.id}" %></label>
        <%= link_to "Update", "tasks/#{t.id}/edit"  %>
        <%= link_to "Delete", "tasks/#{t.id}", method: :delete, data: { confirm: "Are you sure you wish to delete this task?" }   %>
       </div>
    <% else %>
      <div>
        <input type="checkbox" name="task">
        <label for="task"><%= link_to t.title, "tasks/#{t.id}" %></label>
        <%= link_to "Update", "tasks/#{t.id}/edit"  %>
        <%= link_to "Delete", "tasks/#{t.id}", method: :delete, data: { confirm: "Are you sure you wish to delete this task?" }  %>
      </div>
    <% end %>
  <% end %>
</fieldset>

<div>
  <%= link_to "Create a new task", tasks_new_path  %>
</div>
<div>

</div>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title  %></h1>
<p><%= @task.details  %></p>
<p>Status: <% if @task.completed %>
      <div>
        <input type="checkbox" name="task" checked>
        <label for="task">Task completed</label>
       </div>
    <% else %>
      <div>
        <input type="checkbox" name="task">
        <label for="task">Mark as completed</label>
      </div>
    <% end %>
</p>
<%= link_to "Return to list of tasks", tasks_path  %>